dataset: Sim_Hirano_Imbens
output_dir: './'
v_dim: 100
z_dims: [1,1,1,7]
x_min: 0
x_max: 3
lr: 0.0002
bs: 32
alpha: 1
beta: 1
gamma: 10
g_d_freq: 5
g_units: [64,64,64,64,64]
e_units: [64,64,64,64,64]
f_units: [64,32,8]
h_units: [64,32,8]
dz_units: [64,32,8]
dv_units: [64,32,8]
binary_treatment: False
use_z_rec: True
use_v_gan: False
save_model: False